print('game')
adjective = input('Enter first adjective')
animal = input('Enter first animal name')
verbo = input('Enter first verb')
exclamation = input('Enter first exclamation')
verbt = input('Enter second verb')
verbth = input('Enter third verb')
verbf = input('Enter fourth verb')
adjectivet = input('Enter second adjective')
animalt = input('Enter second animal')
verbs = input('Enter fifth verb')
verbse = input('Enter sixth verb')
verbsee = input('Enter seventh verb')
output = f'Your story is: \n\n The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verbo} down the hallway. "{exclamation.capitalize()}!" I yelled. But all I could think to do was to {verbt} over and over. Miraculously, that caused it to stop, but not before it tried to {verbth} right in front of my family. \n\nMy little sister, addicted to {animalt}, {verbf} after seeing a {adjectivet} {animalt} for the first time in her life. "{verbs.capitalize()} it out of here!", she {verbse}. \n\nIt took hours to {verbsee} her down, after such a troubling moment for her.'
print(output)
